
setlocal spell
set spelllang=en_gb
inoremap <C-l> <c-g>u<Esc>[s1z=`]a<c-g>u


" Plugins with vim Plug 
call plug#begin('~/.vim/plugged')


" VIMTEX PLUGINS
Plug 'lervag/vimtex'
let g:tex_flavor='latex'
let g:vimtex_quickfix_mode=0  
set conceallevel=1
let g:tex_conceal='abdmg'
let g:vimtex_motion_matchparen = 0


" ULTISNIPS PLUGINS 
Plug 'sirver/ultisnips'
let g:UltiSnipsExpandTrigger = '<tab>'
let g:UltiSnipsJumpForwardTrigger = '<tab>'
let g:UltiSnipsJumpBackwardTrigger = '<s-tab>'
let g:UltiSnipsEditSplit="vertical"
let g:UltiSnipsSnippetsDir = $HOME.'/.vim/UltiSnips'


" VIMTEX SHORTCUTS 
nnoremap <space> <Nop> 
let mapleader="\<space>"
let maplocalleader="\<space>"


" clear the grey
hi clear Conceal

Plug 'honza/vim-snippets'
call plug#end()
